apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: incidentbot-docs

bases:
  - ../../base/

images:
  - name: eb129/incidentbot-docs
    newTag: v2.1.1

generatorOptions:
  disableNameSuffixHash: true
